#!/usr/bin/awk -f

# line count, to get the baseline performance before pipelining

@include "redis.awk"

BEGIN {
    # ctx = redis_open("redis.hello.org", 6379)
    ctx = redis_open()        # Use env. variable REDIS_ENDPOINT or
                              # the default, "localhost:6379"
}

{
    redis_command(ctx, resp, 2, "INCR", "count")
}

END {
    redis_command(ctx, resp, 2, "GET", "count")
    print resp[0]

    redis_close(ctx)
}

