#!/usr/bin/awk -f

# simple demonstration of redis.awk API

@include "redis.awk"

BEGIN {
    # redis = redis_open("redis.hello.org", 6379)
    ctx = redis_open()        # Use env. variable REDIS_ENDPOINT or
                              # the default, "localhost:6379"
    print "CONTEXT: ", ctx

    redis_command(ctx, resp, 3, "SET", "name", "Seong-Kook Shin")
    redis_command(ctx, resp, 8, "HMSET", "pet", 
                  "name", "Ping",
                  "age", 3,
                  "species", "lovebird")

    redis_command(ctx, resp, 2, "GET", "name")
    redis_dump(resp)            # Dump the response to stderr

    redis_command(ctx, resp, 2, "HGETALL", "pet")
    redis_dump(resp)            # Dump the response to stderr

    redis_close(ctx)
}

